### ISSUE TITLE
Add Slack Sign Up Link

### ISSUE THREAD

**Issue by theryankelly** [codeisland/codeisland.github.io#24]
Link to Google Form https://docs.google.com/forms/d/18kUCl87BrV9FAKk2yCY7BSg3NziwXmkausjt8qvoQoQ/viewform

**Comment by theryankelly** [comment]
Need to find and add icon to site header

**Comment by patekuru** [comment]
Done! As per the 3 commits ending with https://github.com/codeisland/codeisland.github.io/commit/016f60673e41d91e54c44c61972fbab8890511c3

**Comment by goldenmeanie** [comment]
Thanks @patekuru !
